### ISSUE TITLE
Confused on usage of S.Maybe

### ISSUE THREAD

**Issue by Wideshanks** [plaid/sanctuary-def#10]
I get a TypeError from sanctuary-def saying

```
expected to return a value of type (Maybe Number); returned Nothing()`.
```

But I would have expected a `Nothing` to be a valid return type for a function written to return a `Maybe($.Number)`?

Simplified usage below, used with Node v5.20. Error at the bottom.

```javascript
const R = require('ramda');
const S = require('sanctuary');
const $ = require('sanctuary-def');

// Maybe :: Type -> Type
const Maybe = $.UnaryType(
  'my-package/Maybe',
  x => x != null && x['@@type'] === 'my-package/Maybe',
  maybe => maybe.isJust ? [maybe.value] : []
);

const env = $.env.concat([Maybe]);

const def = $.create(env);

// Mock.
//
// availWarps :: Game -> Number -> [Number]
const availWarps =
  def('availWarps', {}, [$.Any, $.Number, $.Array($.Number)],
    (game, sid) => [1]);

// Mock. Would return a transformed game.
//
// move :: Game -> Number -> Number -> Game
const setSector = (game, pid, sid) => game;

// If `sid` appears in what `availWarps` returns: Just(sid). Else Nothing().
//
// isWarpAvailable :: Game -> Number -> Number -> Maybe Number
const isWarpAvailable =
  def('isWarpAvailable', {}, [$.Any, $.Number, $.Number, Maybe($.Number)],
    (game, pid, sid) =>
      S.Maybe.of(sid).filter(x => R.contains(sid, availWarps)));

// If `isWarpAvailable` returned a Just, run `setSector` and return the
// modified game, else return Nothing.
//
// move :: Game -> Number -> Number -> Maybe Game
const move =
  def('move', {}, [$.Any, $.Number, $.Number, Maybe($.Any)],
    (game, pid, sid) =>
      isWarpAvailable(game, pid, sid).extend(_ => setSector(game, pid, sid)));

// main

move({}, 1, 1);

/*
node_modules/sanctuary-def/index.js:714
            throw invalidReturnValue(name, [expRetType], returnValue);
            ^

TypeError: isWarpAvailable is expected to return a value of type (Maybe Number); returned Nothing()
    at invalidReturnValue (node_modules/sanctuary-def/index.js:534:12)
    at node_modules/sanctuary-def/index.js:714:19
    at node_modules/sanctuary-def/index.js:364:20
    at <this file>:64:7
*/
```

**Comment by davidchambers** [comment]
The predicate for your Maybe type is

```javascript
x => x != null && x['@@type'] === 'my-package/Maybe'
```

but I imagine you want

```javascript
x => x != null && x['@@type'] === 'sanctuary/Maybe'
```

since `S.Nothing()['@@type']` evaluates to `'sanctuary/Maybe'`.

**Comment by davidchambers** [comment]
Please reopen this issue, @Wideshanks, if the comment above does not solve your problem.
